/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import dtos.AlumnoDTO;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import negocio.IAlumnoNegocio;
import negocio.NegocioException;

/**
 *
 * @author Rios 233537
 */
public class frmEditarAlumnos extends javax.swing.JFrame {
    frmCRUD pantallaPrincipal;
    AlumnoDTO alumnoDTO;
    IAlumnoNegocio alumnoNegocio;

    /**
     * Creates new form frmEditarAlumnos
     */
    public frmEditarAlumnos(frmCRUD pantallaPrincipal, IAlumnoNegocio alumnoNegocio, AlumnoDTO alumnoDTO) {
        initComponents();
        this.pantallaPrincipal=pantallaPrincipal;
        this.alumnoNegocio= alumnoNegocio;
        this.alumnoDTO = alumnoDTO;
        this.setTitle("Editar Alumno");
        metodosInciales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        iDlabel = new javax.swing.JLabel();
        NombresTxt = new javax.swing.JTextField();
        apellidoMAtxt = new javax.swing.JTextField();
        apellidoPATxt = new javax.swing.JTextField();
        radbtnActivo = new javax.swing.JRadioButton();
        btnCancelar = new javax.swing.JButton();
        btnGuardar1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iDlabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        iDlabel.setText("ID Alumno:");
        jPanel2.add(iDlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 64, 166, -1));
        jPanel2.add(NombresTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 129, 184, 39));
        jPanel2.add(apellidoMAtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 243, 184, 39));
        jPanel2.add(apellidoPATxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 186, 184, 39));

        radbtnActivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radbtnActivo.setText("Activo");
        radbtnActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radbtnActivoActionPerformed(evt);
            }
        });
        jPanel2.add(radbtnActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 300, 107, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 157, 33));

        btnGuardar1.setText("Guardar");
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 157, 33));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void metodosInciales() {

        iDlabel.setText("ID Alumno: " + alumnoDTO.getIdAlumno());
        NombresTxt.setText(alumnoDTO.getNombres());
        apellidoPATxt.setText(alumnoDTO.getApellidoPaterno());
        apellidoMAtxt.setText(alumnoDTO.getApellidoMaterno());
        radbtnActivo.setSelected(alumnoDTO.getEstatus().equalsIgnoreCase("No Eliminado"));
    }
    private void radbtnActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radbtnActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radbtnActivoActionPerformed

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        String nombres = NombresTxt.getText();
        String apellidoPa = apellidoPATxt.getText();
        String apellidoMa = apellidoMAtxt.getText();
        String status = radbtnActivo.isSelected() ? "No Eliminado" : "Eliminado";

        AlumnoDTO edicionAlumno = new AlumnoDTO(alumnoDTO.getIdAlumno(), nombres, apellidoPa, apellidoMa, status);
         int confirmacion = JOptionPane.showOptionDialog(this,
                    "¿Está seguro de que deseas editar al Alumno "+alumnoDTO.getIdAlumno(),
                    "Confirmación de edicion",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    new Object[]{"Confirmar", "Cancelar"},
                    "Confirmar");

            // Si el usuario selecciona "Cancelar", no se hace nada
            if (confirmacion != JOptionPane.YES_OPTION) {
                return;
            }
        try {
            alumnoNegocio.editar(edicionAlumno);
            this.pantallaPrincipal.cargarAlumnosEnTabla();
            dispose();
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEditarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEditarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEditarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEditarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NombresTxt;
    private javax.swing.JTextField apellidoMAtxt;
    private javax.swing.JTextField apellidoPATxt;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JLabel iDlabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton radbtnActivo;
    // End of variables declaration//GEN-END:variables
}
